# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170329_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
