# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:42
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170404_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
